In [2]:
import numpy as np

In [3]:
print(np.__version__)
np.show_config

1.16.2


<function numpy.__config__.show()>

In [5]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [14]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [16]:
C = np.arange(20)
A = C[::-1]
print(C)
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [19]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [20]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [22]:
Z = np.eye(3,3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [28]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.62277471 0.90145026 0.96427379]
  [0.03691379 0.19109129 0.83463589]
  [0.16661872 0.44541853 0.90233209]]

 [[0.64655856 0.64022927 0.81308013]
  [0.32261139 0.65006247 0.15051943]
  [0.96050365 0.2359011  0.79039514]]

 [[0.10269304 0.81614431 0.31860348]
  [0.66694101 0.43485679 0.82204608]
  [0.69468814 0.48347563 0.30196599]]]


In [30]:
Z = np.random.random((10,10))
Zmin,Zmax = Z.min(),Z.max()
print(Zmin,Zmax)

0.002990404529077395 0.9818955926581421


In [52]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.5390432380588529


In [61]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [62]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [67]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


In [71]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [72]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [73]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [74]:
color = np.dtype([("r", np.ubyte, 1),
                   ("g", np.ubyte, 1),
                   ("b", np.ubyte, 1),
                   ("a", np.ubyte, 1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [75]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [76]:
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [86]:
print(sum(range(5),-1))

10


In [88]:
from numpy import *
print(sum(range(5),-1))

10


##自带sum 和numpy sum https://blog.csdn.net/lyl771857509/article/details/84047421

In [91]:
Z = np.arange(5)
Z ** Z  # legal
2 << Z >> 2  # false
Z <- Z   # legal
1j*Z   # legal
Z/1/1   # legal
Z<Z>Z    # false

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [93]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


c:\users\rjtit\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
c:\users\rjtit\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


In [95]:
Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[ 5.  5. -7. -5. -8.  7.  3.  5. 10. -1.]


In [99]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[0 1 5 8 9]


In [106]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

An equivalent way, with a context manager:
    
with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

SyntaxError: invalid syntax (<ipython-input-106-e259dcc7f2fe>, line 8)

In [107]:
np.sqrt(-1) == np.emath.sqrt(-1)  # False

c:\users\rjtit\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

In [110]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print ("Yesterday is " + str(yesterday))
print ("Today is " + str(today))
print ("Tomorrow is "+ str(tomorrow))

Yesterday is 2019-06-22
Today is 2019-06-23
Tomorrow is 2019-06-24


In [112]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [113]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)

array([3., 3., 3.])

In [114]:
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[0. 4. 6. 5. 1. 0. 9. 0. 2. 2.]
[0. 4. 6. 5. 1. 0. 9. 0. 2. 2.]
[0. 4. 6. 5. 1. 0. 9. 0. 2. 2.]
[0 4 6 5 1 0 9 0 2 2]
[0. 4. 6. 5. 1. 0. 9. 0. 2. 2.]


In [115]:
Z = np.zeros((5,5))
Z += np.arange(5)
print (Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [116]:
def generate():
   for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print (Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [118]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print (Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [119]:
Z = np.random.random(10)
Z.sort()
print (Z)

[0.10625082 0.262092   0.26959875 0.28804339 0.46155715 0.57720232
 0.58804598 0.68096965 0.73963381 0.86082738]


In [120]:
Z = np.arange(10)
np.add.reduce(Z)

45

In [123]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)
# # 方法2
# # Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


In [124]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

In [125]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print (R)
print (T)

[1.25025247 1.28131193 0.17210718 0.62568686 0.66329004 0.78771729
 0.76203638 0.71606948 0.76514389 0.35790964]
[0.82689377 0.82268546 1.19452532 1.45704106 1.10237706 1.4512475
 1.54022066 0.05306031 0.82456283 0.03467854]


In [126]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print (Z)

[0.60138445 0.         0.15588304 0.85340472 0.16043591 0.41809229
 0.66204699 0.47357637 0.68923707 0.00559063]


In [127]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                              np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [128]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


In [136]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [135]:
# np.set_printoptions(threshold= np.nan)
# np.set_printoptions(threshold= "nan")
Z = np.zeros((16,16))
print (Z)

ValueError: threshold must be numeric and non-NAN, try sys.maxsize for untruncated representation

In [ ]:
↑49 

In [137]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print (Z[index])

3


In [138]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print (Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


In [139]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print (D)
# # 方法2
# # Much faster with scipy
# import scipy
# # Thanks Gavin Heverly-Coulson (#issue 1)
# import scipy.spatial
# D = scipy.spatial.distance.cdist(Z,Z)
# print (D)

[[0.         0.57508277 0.66492234 0.43306093 0.55715451 0.50198344
  0.66423384 0.10664105 0.45805449 0.45378771]
 [0.57508277 0.         0.13567206 0.66579046 0.22670098 0.14050439
  0.17166035 0.47065696 0.37225931 0.1403018 ]
 [0.66492234 0.13567206 0.         0.67145306 0.17996232 0.2761667
  0.26569375 0.5583063  0.35908944 0.21163397]
 [0.43306093 0.66579046 0.67145306 0.         0.49444319 0.68636624
  0.82378241 0.41048614 0.31344138 0.53042834]
 [0.55715451 0.22670098 0.17996232 0.49444319 0.         0.33019067
  0.39734474 0.45361013 0.18100957 0.16786237]
 [0.50198344 0.14050439 0.2761667  0.68636624 0.33019067 0.
  0.16245504 0.40631729 0.43088596 0.17843428]
 [0.66423384 0.17166035 0.26569375 0.82378241 0.39734474 0.16245504
  0.         0.56864616 0.54086436 0.29396107]
 [0.10664105 0.47065696 0.5583063  0.41048614 0.45361013 0.40631729
  0.56864616 0.         0.36923015 0.34729601]
 [0.45805449 0.37225931 0.35908944 0.31344138 0.18100957 0.43088596
  0.54086436 0.369230

In [ ]:
Z = np.arange(10, dtype=np.int32)
Z = Z.astype(np.float32, copy=False)
print (Z)

In [140]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print (index, value)
for index in np.ndindex(Z.shape):
    print (index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [141]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print (G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [142]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print (Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


In [143]:
X = np.random.rand(5, 10)
# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[-0.00627389  0.09809016 -0.26383572 -0.45383916  0.41044954  0.31627147
   0.34232858 -0.06977212  0.09952836 -0.47294722]
 [-0.00765257 -0.12894709 -0.01345917  0.07661699  0.44385709 -0.5083264
  -0.22944862  0.25213141 -0.12207831  0.23730666]
 [-0.41946597  0.31542002  0.10557898 -0.28495632 -0.4544398   0.37725737
   0.05925761 -0.18206114  0.41981091  0.06359833]
 [ 0.49203695  0.39001749 -0.09202543 -0.30003697  0.17919839 -0.38414557
   0.37683911 -0.36297138 -0.27131811 -0.02759449]
 [-0.36812082 -0.21852955 -0.36605888 -0.0033507  -0.26783661  0.16369822
   0.4284841   0.56330567  0.35672137 -0.28831281]]


In [144]:
Z = np.random.randint(0,10,(3,3))
print (Z)
print (Z[Z[:,1].argsort()])

[[0 9 1]
 [5 0 2]
 [6 2 1]]
[[5 0 2]
 [6 2 1]
 [0 9 1]]


In [145]:
Z = np.random.randint(0,3,(3,10))
print ((~Z.any(axis=0)).any())

True


In [146]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print (m)

0.5310792331041165


In [147]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: 
    z[...] = x + y
print (it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [148]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


In [149]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[5. 1. 3. 4. 2. 2. 2. 4. 2. 5.]


In [150]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print (F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [151]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
#Note that we should compute 256*256 first. 
#Otherwise numpy will only promote F.dtype to 'uint16' and overfolw will occur
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print (n)

8


In [152]:
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print (sum)

3


In [153]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print (D_means)

[0.61004031 0.58098188 0.59469754 0.54685193 0.48644463 0.52977501
 0.43832689 0.31881438 0.42808358 0.40027558]


In [156]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
# slow version
np.diag(np.dot(A, B))
# 方法2
# Fast version
np.sum(A * B.T, axis=1)
## 方法3
# # Faster version
np.einsum("ij,ji->i", A, B)

array([0.9703776 , 1.91107035, 0.84952589, 0.48833561, 0.60468454])

In [157]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print (Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [158]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print (A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [159]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print (G)

[( 3, 33) ( 3, 37) ( 7, 46) ( 7, 66) (14, 19) (14, 39) (17, 61) (17, 95)
 (19, 21) (19, 39) (19, 58) (21, 58) (25, 39) (25, 98) (29, 41) (29, 68)
 (33, 37) (36, 55) (36, 62) (39, 98) (41, 68) (46, 66) (51, 71) (51, 85)
 (52, 54) (52, 98) (54, 98) (55, 62) (61, 95) (71, 85)]


In [160]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print (A)

[1 1 2 3 4 4 6]


In [161]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)

print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [162]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)

print (Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [163]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

array([0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1])

In [164]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))

print (distance(P0, P1, p))

[0.11260541 2.73475691 8.9761268  1.78567882 5.9436111  2.36369837
 6.81435827 3.6594594  1.76978256 4.92313411]


In [165]:
# based on distance function from previous question
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print (np.array([distance(P0,P1,p_i) for p_i in p]))

[[12.06001146  0.38541018  3.27061684  6.1389589   4.15419195  0.30673419
  16.05657077 15.93680959 10.35615918 10.01254603]
 [ 8.60010356  1.18944208  6.01374565  5.06069718 10.29571363 11.15318033
   5.16594375  4.46614815 14.8418295  10.21596299]
 [ 7.37484296 16.47918884  7.12161867 12.10593819  6.07260698 13.9106974
   0.16076745 12.20569547  2.35382164  7.29985581]
 [ 5.19090658  2.01875028  4.47352786  1.6720526   7.81120897 12.87276041
   3.07666109  4.74888457 12.02700399  6.89413206]
 [ 5.84665258  6.29187504  6.21118627  0.06599217  0.48048688  2.70770941
  12.3567117  16.59678227  5.13571137  3.91442806]
 [ 2.12376295 11.21092897  4.01548197  6.72681701  1.65978738 11.91924418
   2.7855528  10.97485286  2.4784467   1.94153234]
 [ 6.73169422  3.95673514  2.4379679   1.54787595  2.85853021  5.28241103
  10.17170532 12.86698278  8.14979332  5.88844285]
 [ 1.70844469  6.83776011  0.56206589  2.54292589  2.50828128 11.52856225
   3.74175177  8.79046088  6.80816812  2.35996258]
 

In [166]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print (Z)
print (R)

[[7 0 7 9 0 3 5 1 8 8]
 [1 7 3 1 2 3 2 2 8 0]
 [9 0 3 2 2 0 8 0 8 8]
 [0 6 0 9 4 7 8 1 8 4]
 [9 3 7 0 1 8 4 1 3 7]
 [2 4 1 2 2 2 7 3 7 7]
 [4 9 9 6 2 5 4 3 6 7]
 [3 3 8 6 9 6 1 9 0 1]
 [6 9 2 4 8 1 0 3 9 7]
 [2 6 3 3 2 8 8 0 0 7]]
[[0 0 0 0 0]
 [0 7 0 7 9]
 [0 1 7 3 1]
 [0 9 0 3 2]
 [0 0 6 0 9]]


c:\users\rjtit\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


In [167]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print (R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [168]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print (rank)

10


In [169]:
Z = np.random.randint(0,10,50)
print (np.bincount(Z).argmax())

1


In [170]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print (C)

[[[[3 0 3]
   [2 2 3]
   [0 0 0]]

  [[0 3 3]
   [2 3 2]
   [0 0 1]]

  [[3 3 0]
   [3 2 3]
   [0 1 0]]

  [[3 0 4]
   [2 3 3]
   [1 0 3]]

  [[0 4 2]
   [3 3 4]
   [0 3 2]]

  [[4 2 0]
   [3 4 2]
   [3 2 2]]

  [[2 0 2]
   [4 2 2]
   [2 2 4]]

  [[0 2 0]
   [2 2 4]
   [2 4 4]]]


 [[[2 2 3]
   [0 0 0]
   [4 1 4]]

  [[2 3 2]
   [0 0 1]
   [1 4 2]]

  [[3 2 3]
   [0 1 0]
   [4 2 2]]

  [[2 3 3]
   [1 0 3]
   [2 2 4]]

  [[3 3 4]
   [0 3 2]
   [2 4 2]]

  [[3 4 2]
   [3 2 2]
   [4 2 0]]

  [[4 2 2]
   [2 2 4]
   [2 0 4]]

  [[2 2 4]
   [2 4 4]
   [0 4 2]]]


 [[[0 0 0]
   [4 1 4]
   [2 2 3]]

  [[0 0 1]
   [1 4 2]
   [2 3 4]]

  [[0 1 0]
   [4 2 2]
   [3 4 1]]

  [[1 0 3]
   [2 2 4]
   [4 1 3]]

  [[0 3 2]
   [2 4 2]
   [1 3 3]]

  [[3 2 2]
   [4 2 0]
   [3 3 4]]

  [[2 2 4]
   [2 0 4]
   [3 4 3]]

  [[2 4 4]
   [0 4 2]
   [4 3 3]]]


 [[[4 1 4]
   [2 2 3]
   [0 3 3]]

  [[1 4 2]
   [2 3 4]
   [3 3 3]]

  [[4 2 2]
   [3 4 1]
   [3 3 3]]

  [[2 2 4]
   [4 1 3]
   [3 3 0]]

  [[2 4 2]
   

In [171]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print (S)

[[ 8 15 16  4  6]
 [15  8  5  9  1]
 [16  5  9 42 13]
 [ 4  9 42  1  7]
 [ 6  1 13  7  1]]


In [172]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print (S)
It works, because:
M is (p,n,n)
V is (p,n,1)
Thus, summing over the paired axes 0 and 0 (of M and V independently),
and 2 and 1, to remain with a (n,1) vector.

SyntaxError: invalid syntax (<ipython-input-172-bee018737b0e>, line 6)

In [173]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print (S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [174]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print (Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 1 1 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [175]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])
# 方法2
# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9997 9998 9999 9996 9995]


In [176]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [177]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print (R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [179]:
x = np.random.rand()
np.power(x,3)
# # 方法2
# x*x*x
# # 方法3
# np.einsum('i,i,i->i',x,x,x)

0.016624361461383474

In [180]:
Z = np.random.randint(0,5,(10,3))
print (Z)

# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print (U)
# # 方法2
# # soluiton for numerical arrays only, will work for any number of columns in Z
# U = Z[Z.max(axis=1) != Z.min(axis=1),:]
# print (U)

[[4 2 0]
 [2 3 1]
 [0 2 2]
 [3 4 2]
 [3 0 0]
 [2 4 3]
 [4 4 1]
 [3 2 3]
 [1 1 4]
 [2 3 2]]
[[4 2 0]
 [2 3 1]
 [0 2 2]
 [3 4 2]
 [3 0 0]
 [2 4 3]
 [4 4 1]
 [3 2 3]
 [1 1 4]
 [2 3 2]]


In [181]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])
# # 方法2
# print (np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [182]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print (uZ)

[[0 1 1]
 [1 0 0]
 [1 1 0]]


In [184]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
print ('sum')
print (np.einsum('i->', A))# np.sum(A)
print ('A * B')
print (np.einsum('i,i->i', A, B)) # A * B
print ('inner')
print (np.einsum('i,i', A, B))    # np.inner(A, B)
print ('outer')
print (np.einsum('i,j->ij', A, B))    # np.outer(A, B)

sum
5.115968287549821
A * B
[0.08253462 0.28554142 0.06308721 0.20644273 0.40939107 0.23845969
 0.34966514 0.03061042 0.29885975 0.5311769 ]
inner
2.495768950991862
outer
[[0.08253462 0.05938118 0.03509474 0.06015244 0.07875407 0.03400036
  0.04579977 0.07532893 0.06104762 0.06702602]
 [0.39687748 0.28554142 0.16875722 0.2892501  0.37869826 0.16349473
  0.22023359 0.36222806 0.29355472 0.32230252]
 [0.14836635 0.10674513 0.06308721 0.10813156 0.14157034 0.06111991
  0.08233083 0.13541321 0.10974078 0.12048769]
 [0.28325823 0.20379578 0.12044491 0.20644273 0.27028341 0.11668898
  0.15718447 0.25852834 0.20951501 0.23003281]
 [0.42904369 0.30868404 0.18243469 0.3126933  0.40939107 0.17674569
  0.23808312 0.39158599 0.3173468  0.34842456]
 [0.57885218 0.41646675 0.24613511 0.42187591 0.55233749 0.23845969
  0.32121422 0.52831544 0.42815427 0.4700834 ]
 [0.63012287 0.45335448 0.26793605 0.45924274 0.6012597  0.25958079
  0.34966514 0.57510994 0.4660772  0.51172012]
 [0.0335385  0.02412994 

In [186]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

In [187]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print (X[M])

[[2. 0. 1. 1.]]


In [188]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print (confint)

[-0.00347332  0.3991352 ]
